version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - deals-api
      - listings-api
      - investor-profiles-api
      - mortgages-api
      - underwritings-api
      - subscriptions-api
    networks:
      - zimba-rei-common-components
    restart: always

  deals-api:
    build: deals_api
    volumes:
      - ./deals_api:/app
    networks:
      - zimba-rei-common-components
    restart: always
#    command: [ "uvicorn", "main.py:app", "--host", "0.0.0.0", "--port", "8000" ]
#    healthcheck:
#      test: curl --fail http://localhost:8000/health || exit 1
#      interval: 2s
#      timeout: 5s
#      retries: 3
#      start_period: 5s

  listings-api:
    build: listings_api
    volumes:
      - ./listings_api:/app
    networks:
      - zimba-rei-common-components
    restart: always

  investor-profiles-api:
    build: investor_profiles_api
    volumes:
      - ./investor_profiles_api:/app
    networks:
      - zimba-rei-common-components
    restart: always

  mortgages-api:
    build: mortgages_api
    volumes:
      - ./mortgages_api:/app
    networks:
      - zimba-rei-common-components
    restart: always

  subscriptions-api:
    build: subscriptions_api
    volumes:
      - ./subscriptions_api:/app
    networks:
      - zimba-rei-common-components
    restart: always

  underwritings-api:
    build: underwritings_api
    volumes:
      - ./underwritings_api:/app
    networks:
      - zimba-rei-common-components
    restart: always

networks:
  zimba-rei-common-components:
      driver: bridge